-- Migracion aditiva: equipos estables, historia organizacional y plazas temporales.
-- Ejecutar una vez en Supabase SQL Editor. No elimina ni renombra campos existentes.
begin;

do $$
declare v_column text;
begin
  if to_regclass('public.activadores') is null or to_regclass('public.activaciones') is null then
    raise exception 'Preflight: deben existir public.activadores y public.activaciones';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'activadores' and column_name = 'usuario_id' and udt_name = 'uuid'
  ) or not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'activaciones' and column_name = 'usuario_id' and udt_name = 'uuid'
  ) then
    raise exception 'Preflight: activadores.usuario_id y activaciones.usuario_id deben ser uuid';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'activadores' and column_name = 'lider_id' and udt_name = 'uuid'
  ) then
    raise exception 'Preflight: activadores.lider_id debe ser uuid';
  end if;
  if not exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'activaciones' and column_name = 'es_plaza_temporal' and udt_name = 'bool'
  ) then
    raise exception 'Preflight: activaciones.es_plaza_temporal debe ser boolean';
  end if;
  foreach v_column in array array['nombre','rol','estado','lider_id','plaza'] loop
    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'activadores' and column_name = v_column) then
      raise exception 'Preflight: falta activadores.%', v_column;
    end if;
  end loop;
  foreach v_column in array array['created_at','fecha_activacion','ciudad_activacion','es_plaza_temporal','plaza_temporal'] loop
    if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'activaciones' and column_name = v_column) then
      raise exception 'Preflight: falta activaciones.%', v_column;
    end if;
  end loop;
end;
$$;

create extension if not exists pgcrypto;
create extension if not exists btree_gist;
create extension if not exists unaccent;

-- La columna normalizada se mantiene con trigger porque unaccent no es IMMUTABLE.
create or replace function public.normalizar_nombre_plaza()
returns trigger language plpgsql set search_path = public
as $$
begin
  new.nombre := btrim(new.nombre);
  new.nombre_normalizado := lower(unaccent(btrim(new.nombre)));
  return new;
end;
$$;

create table if not exists public.plazas (
  id uuid primary key default gen_random_uuid(),
  nombre text not null check (btrim(nombre) <> ''),
  nombre_normalizado text not null unique,
  activa boolean not null default true,
  created_at timestamptz not null default now()
);
drop trigger if exists trg_normalizar_nombre_plaza on public.plazas;
create trigger trg_normalizar_nombre_plaza
before insert or update of nombre on public.plazas
for each row execute function public.normalizar_nombre_plaza();

alter table public.activadores add column if not exists plaza_base text;
alter table public.activadores add column if not exists plaza_id uuid references public.plazas(id);
alter table public.activadores add column if not exists organizacion_pendiente boolean not null default false;
update public.activadores set plaza_base = plaza
where nullif(btrim(plaza_base), '') is null and nullif(btrim(plaza), '') is not null;

insert into public.plazas(nombre, nombre_normalizado)
select min(nombre), nombre_normalizado
from (
  select btrim(coalesce(plaza_base, plaza)) nombre,
         lower(unaccent(btrim(coalesce(plaza_base, plaza)))) nombre_normalizado
  from public.activadores where nullif(btrim(coalesce(plaza_base, plaza)), '') is not null
  union all
  select btrim(ciudad_activacion), lower(unaccent(btrim(ciudad_activacion)))
  from public.activaciones where nullif(btrim(ciudad_activacion), '') is not null
) existentes
group by nombre_normalizado
on conflict (nombre_normalizado) do nothing;

create table if not exists public.facturadores (
  id uuid primary key default gen_random_uuid(),
  codigo text not null unique,
  nombre text not null,
  activo boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.equipos (
  id uuid primary key default gen_random_uuid(),
  numero bigint generated by default as identity unique not null,
  nombre text not null,
  facturador_id uuid not null references public.facturadores(id),
  plaza_id uuid not null references public.plazas(id),
  lider_actual_id uuid references public.activadores(usuario_id),
  activo boolean not null default true,
  created_at timestamptz not null default now(),
  unique (id, plaza_id)
);
create unique index if not exists ux_equipos_fallback_facturador_plaza
  on public.equipos(facturador_id, plaza_id) where nombre = 'Equipo sin asignar';
create unique index if not exists ux_equipos_lider_plaza_activo
  on public.equipos(lider_actual_id, plaza_id)
  where activo and lider_actual_id is not null;

create table if not exists public.equipo_lider_historial (
  id uuid primary key default gen_random_uuid(),
  equipo_id uuid not null,
  plaza_id uuid not null references public.plazas(id) on delete restrict,
  lider_id uuid not null references public.activadores(usuario_id) on delete restrict,
  inicio timestamptz not null,
  fin timestamptz,
  autorizado_por uuid references auth.users(id),
  motivo text,
  created_at timestamptz not null default now(),
  constraint equipo_lider_fechas_validas check (fin is null or fin > inicio),
  constraint equipo_lider_equipo_plaza_fk foreign key (equipo_id, plaza_id)
    references public.equipos(id, plaza_id) on delete restrict,
  constraint equipo_lider_unico_periodo exclude using gist
    (equipo_id with =, tstzrange(inicio, fin, '[)') with &&),
  constraint lider_plaza_unico_periodo exclude using gist
    (lider_id with =, plaza_id with =, tstzrange(inicio, fin, '[)') with &&)
);

alter table public.activadores add column if not exists equipo_id uuid references public.equipos(id);

create table if not exists public.activador_equipo_historial (
  id uuid primary key default gen_random_uuid(),
  activador_id uuid not null references public.activadores(usuario_id) on delete restrict,
  equipo_id uuid not null references public.equipos(id) on delete restrict,
  inicio timestamptz not null,
  fin timestamptz,
  autorizado_por uuid references auth.users(id),
  motivo text,
  created_at timestamptz not null default now(),
  constraint activador_equipo_fechas_validas check (fin is null or fin > inicio),
  exclude using gist (activador_id with =, tstzrange(inicio, fin, '[)') with &&)
);

create table if not exists public.activador_plaza_temporal (
  id uuid primary key default gen_random_uuid(),
  activador_id uuid not null references public.activadores(usuario_id) on delete restrict,
  plaza_temporal_id uuid not null references public.plazas(id) on delete restrict,
  plaza_temporal text not null check (btrim(plaza_temporal) <> ''),
  inicio timestamptz not null,
  fin timestamptz not null,
  motivo text not null check (btrim(motivo) <> ''),
  autorizado_por uuid not null references auth.users(id),
  cancelado_at timestamptz,
  cancelado_por uuid references auth.users(id),
  created_at timestamptz not null default now(),
  constraint plaza_temporal_fechas_validas check (fin > inicio),
  exclude using gist (
    activador_id with =,
    tstzrange(inicio, fin, '[)') with &&
  ) where (cancelado_at is null)
);

alter table public.activaciones add column if not exists equipo_id_registro uuid references public.equipos(id);
alter table public.activaciones add column if not exists plaza_id_registro uuid references public.plazas(id);
alter table public.activaciones add column if not exists plaza_base_id_registro uuid references public.plazas(id);
alter table public.activaciones add column if not exists plaza_efectiva_id_registro uuid references public.plazas(id);
alter table public.activaciones add column if not exists equipo_numero_registro bigint;
alter table public.activaciones add column if not exists equipo_nombre_registro text;
alter table public.activaciones add column if not exists facturador_id_registro uuid references public.facturadores(id);
alter table public.activaciones add column if not exists facturador_nombre_registro text;
alter table public.activaciones add column if not exists lider_id_registro uuid references public.activadores(usuario_id);
alter table public.activaciones add column if not exists lider_nombre_registro text;
alter table public.activaciones add column if not exists plaza_base_registro text;
alter table public.activaciones add column if not exists plaza_efectiva_registro text;
alter table public.activaciones add column if not exists plaza_temporal_registro boolean not null default false;
alter table public.activaciones add column if not exists plaza_temporal_asignacion_id uuid references public.activador_plaza_temporal(id);

insert into public.facturadores (codigo, nombre)
values ('LEGACY', 'Facturador principal')
on conflict (codigo) do nothing;

-- Solo se vinculan plazas que coinciden exactamente despues de normalizar.
update public.activadores a
set plaza_id = p.id
from public.plazas p
where a.rol = 'activador'
  and nullif(btrim(coalesce(a.plaza_base, a.plaza)), '') is not null
  and p.nombre_normalizado = lower(unaccent(btrim(coalesce(a.plaza_base, a.plaza))));

-- Un equipo estable por facturador + lider + plaza observada en sus activadores.
insert into public.equipos (nombre, facturador_id, plaza_id, lider_actual_id)
select 'Equipo ' || coalesce(l.nombre, l.usuario_id::text) || ' - ' || p.nombre,
       f.id, p.id, l.usuario_id
from public.activadores l
join (
  select distinct lider_id, lower(unaccent(btrim(coalesce(plaza_base, plaza)))) plaza_normalizada
  from public.activadores
  where rol = 'activador' and lider_id is not null
    and nullif(btrim(coalesce(plaza_base, plaza)), '') is not null
) asignacion on asignacion.lider_id = l.usuario_id
join public.plazas p on p.nombre_normalizado = asignacion.plaza_normalizada
cross join public.facturadores f
where l.rol = 'lider' and f.codigo = 'LEGACY'
  and not exists (
    select 1 from public.equipos e
    where e.lider_actual_id = l.usuario_id and e.plaza_id = p.id and e.activo
  )
on conflict do nothing;

-- Los activadores sin lider reciben el equipo sin asignar de SU plaza, nunca uno arbitrario.
insert into public.equipos (nombre, facturador_id, plaza_id)
select 'Equipo sin asignar', f.id, p.id
from public.facturadores f
join public.plazas p on exists (
  select 1 from public.activadores a
  where a.rol = 'activador' and a.lider_id is null
    and lower(unaccent(btrim(coalesce(a.plaza_base, a.plaza)))) = p.nombre_normalizado
)
where f.codigo = 'LEGACY'
  and not exists (
    select 1 from public.equipos e where e.nombre = 'Equipo sin asignar'
      and e.facturador_id = f.id and e.plaza_id = p.id
  )
on conflict do nothing;

update public.activadores a
set equipo_id = coalesce(a.equipo_id, e.id),
    plaza_id = p.id,
    organizacion_pendiente = false
from public.plazas p
join public.equipos e on e.plaza_id = p.id and e.activo
join public.facturadores f on f.id = e.facturador_id and f.codigo = 'LEGACY'
where a.rol = 'activador'
  and lower(unaccent(btrim(coalesce(a.plaza_base, a.plaza)))) = p.nombre_normalizado
  and ((a.lider_id is not null and e.lider_actual_id = a.lider_id)
       or (a.lider_id is null and e.lider_actual_id is null and e.nombre = 'Equipo sin asignar'));

-- Los casos sin fuente confiable permanecen sin plaza/equipo y se atienden desde el portal.
update public.activadores
set organizacion_pendiente = true
where rol = 'activador' and (plaza_id is null or equipo_id is null);

insert into public.equipo_lider_historial (equipo_id, plaza_id, lider_id, inicio, motivo)
select e.id, e.plaza_id, e.lider_actual_id, now(), 'Migracion inicial'
from public.equipos e
where e.lider_actual_id is not null
  and not exists (select 1 from public.equipo_lider_historial h where h.equipo_id = e.id and h.fin is null);

insert into public.activador_equipo_historial (activador_id, equipo_id, inicio, motivo)
select a.usuario_id, a.equipo_id, now(), 'Migracion inicial'
from public.activadores a
where a.rol = 'activador' and a.equipo_id is not null
  and not exists (select 1 from public.activador_equipo_historial h where h.activador_id = a.usuario_id and h.fin is null);

create or replace function public.asignar_lider_equipo(
  p_equipo_id uuid, p_lider_id uuid, p_inicio timestamptz default now(), p_motivo text default null
)
returns void language plpgsql security definer set search_path = public
as $$
declare v_plaza_id uuid;
begin
  if not exists (select 1 from public.activadores where usuario_id = p_lider_id and rol = 'lider' and estado = 'activo') then
    raise exception 'El lider debe existir y estar activo';
  end if;
  select plaza_id into v_plaza_id from public.equipos where id = p_equipo_id and activo;
  if v_plaza_id is null then raise exception 'El equipo no existe o esta inactivo'; end if;
  update public.equipo_lider_historial set fin = p_inicio
  where equipo_id = p_equipo_id and fin is null and inicio < p_inicio;
  insert into public.equipo_lider_historial(equipo_id,plaza_id,lider_id,inicio,autorizado_por,motivo)
  values (p_equipo_id,v_plaza_id,p_lider_id,p_inicio,auth.uid(),p_motivo);
  update public.equipos set lider_actual_id = p_lider_id where id = p_equipo_id;
  -- Campo legado conservado para clientes que aun no consumen equipo_id.
  update public.activadores set lider_id = p_lider_id where equipo_id = p_equipo_id and rol = 'activador';
end;
$$;

create or replace function public.asignar_activador_equipo(
  p_activador_id uuid, p_equipo_id uuid, p_inicio timestamptz default now(), p_motivo text default null
)
returns void language plpgsql security definer set search_path = public
as $$
declare v_lider uuid; v_plaza_id uuid; v_plaza_nombre text;
begin
  if not exists (select 1 from public.activadores where usuario_id = p_activador_id and rol = 'activador') then
    raise exception 'El activador no existe';
  end if;
  select e.lider_actual_id, p.id, p.nombre into v_lider, v_plaza_id, v_plaza_nombre
  from public.equipos e join public.plazas p on p.id = e.plaza_id
  where e.id = p_equipo_id and e.activo;
  if v_plaza_id is null then raise exception 'El equipo no existe o esta inactivo'; end if;
  update public.activador_equipo_historial set fin = p_inicio
  where activador_id = p_activador_id and fin is null and inicio < p_inicio;
  insert into public.activador_equipo_historial(activador_id,equipo_id,inicio,autorizado_por,motivo)
  values (p_activador_id,p_equipo_id,p_inicio,auth.uid(),p_motivo);
  update public.activadores set equipo_id = p_equipo_id, lider_id = v_lider,
    plaza_id = v_plaza_id, plaza_base = v_plaza_nombre, plaza = v_plaza_nombre,
    organizacion_pendiente = false
  where usuario_id = p_activador_id;
end;
$$;

create or replace function public.asignar_equipos_lider(
  p_lider_id uuid,
  p_equipo_ids uuid[],
  p_inicio timestamptz default now(),
  p_motivo text default null
)
returns void language plpgsql security definer set search_path = public
as $$
declare v_equipo public.equipos%rowtype; v_ids uuid[] := coalesce(p_equipo_ids, array[]::uuid[]);
begin
  if cardinality(v_ids) > 0 and not exists (
    select 1 from public.activadores
    where usuario_id = p_lider_id and rol = 'lider' and estado = 'activo'
  ) then
    raise exception 'El lider debe existir y estar activo';
  end if;
  if (select count(*) from public.equipos where id = any(v_ids) and activo) <> cardinality(v_ids) then
    raise exception 'Uno o mas equipos no existen o estan inactivos';
  end if;
  if exists (
    select plaza_id from public.equipos where id = any(v_ids)
    group by plaza_id having count(*) > 1
  ) then
    raise exception 'Un lider no puede dirigir dos equipos activos en la misma plaza';
  end if;

  update public.equipo_lider_historial set fin = p_inicio
  where fin is null and inicio < p_inicio
    and (lider_id = p_lider_id or equipo_id = any(v_ids))
    and not (lider_id = p_lider_id and equipo_id = any(v_ids));
  update public.activadores set lider_id = null
  where rol = 'activador' and equipo_id in (
    select id from public.equipos
    where lider_actual_id = p_lider_id and not (id = any(v_ids))
  );
  update public.equipos set lider_actual_id = null
  where lider_actual_id = p_lider_id and not (id = any(v_ids));

  for v_equipo in select * from public.equipos where id = any(v_ids) order by numero loop
    if v_equipo.lider_actual_id is distinct from p_lider_id then
      update public.equipo_lider_historial set fin = p_inicio
      where equipo_id = v_equipo.id and fin is null and inicio < p_inicio;
      insert into public.equipo_lider_historial(equipo_id,plaza_id,lider_id,inicio,autorizado_por,motivo)
      values (v_equipo.id,v_equipo.plaza_id,p_lider_id,p_inicio,auth.uid(),p_motivo);
      update public.equipos set lider_actual_id = p_lider_id where id = v_equipo.id;
      update public.activadores set lider_id = p_lider_id
      where equipo_id = v_equipo.id and rol = 'activador';
    end if;
  end loop;
end;
$$;

create or replace function public.actualizar_equipo_organizacion(
  p_equipo_id uuid,
  p_nombre text,
  p_facturador_id uuid,
  p_lider_id uuid,
  p_activo boolean,
  p_inicio timestamptz default now(),
  p_motivo text default null
)
returns void language plpgsql security definer set search_path = public
as $$
declare v_equipo public.equipos%rowtype; v_lider_final uuid;
begin
  select * into v_equipo from public.equipos where id = p_equipo_id for update;
  if v_equipo.id is null then raise exception 'El equipo no existe'; end if;
  if nullif(btrim(p_nombre), '') is null then raise exception 'El nombre es obligatorio'; end if;
  if not exists (select 1 from public.facturadores where id = p_facturador_id and activo) then
    raise exception 'El facturador no existe o esta inactivo';
  end if;
  v_lider_final := case when p_activo then p_lider_id else null end;
  if v_lider_final is not null and not exists (
    select 1 from public.activadores where usuario_id = v_lider_final and rol = 'lider' and estado = 'activo'
  ) then raise exception 'El lider no existe o esta inactivo'; end if;
  if v_lider_final is not null and exists (
    select 1 from public.equipos
    where id <> p_equipo_id and activo and lider_actual_id = v_lider_final and plaza_id = v_equipo.plaza_id
  ) then raise exception 'El lider ya dirige un equipo activo en esta plaza'; end if;

  if v_equipo.lider_actual_id is distinct from v_lider_final or v_equipo.activo is distinct from p_activo then
    update public.equipo_lider_historial set fin = p_inicio
    where equipo_id = p_equipo_id and fin is null and inicio < p_inicio;
  end if;
  update public.equipos set nombre = btrim(p_nombre), facturador_id = p_facturador_id,
    lider_actual_id = v_lider_final, activo = p_activo
  where id = p_equipo_id;
  if v_lider_final is not null and v_equipo.lider_actual_id is distinct from v_lider_final then
    insert into public.equipo_lider_historial(equipo_id,plaza_id,lider_id,inicio,autorizado_por,motivo)
    values (p_equipo_id,v_equipo.plaza_id,v_lider_final,p_inicio,auth.uid(),p_motivo);
  end if;
  update public.activadores set lider_id = v_lider_final
  where equipo_id = p_equipo_id and rol = 'activador';
end;
$$;

create or replace function public.registrar_cambio_equipo_activador()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  if new.rol = 'activador' and new.equipo_id is not null then
    if tg_op = 'UPDATE' and old.equipo_id is not distinct from new.equipo_id then
      return new;
    end if;
    if exists (
      select 1 from public.activador_equipo_historial
      where activador_id = new.usuario_id and equipo_id = new.equipo_id and fin is null
    ) then
      return new;
    end if;
    update public.activador_equipo_historial set fin = now()
    where activador_id = new.usuario_id and fin is null;
    if not exists (
      select 1 from public.activador_equipo_historial
      where activador_id = new.usuario_id and equipo_id = new.equipo_id and fin is null
    ) then
      insert into public.activador_equipo_historial(activador_id,equipo_id,inicio,autorizado_por,motivo)
      values (new.usuario_id,new.equipo_id,now(),auth.uid(),'Actualizacion de activador');
    end if;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_registrar_cambio_equipo_activador on public.activadores;
create trigger trg_registrar_cambio_equipo_activador
after insert or update on public.activadores
for each row execute function public.registrar_cambio_equipo_activador();

create or replace function public.plaza_efectiva_activador(
  p_activador_id uuid,
  p_momento timestamptz default now()
)
returns table (plaza_base text, plaza_efectiva text, es_temporal boolean, asignacion_id uuid, plaza_efectiva_id uuid)
language sql stable security definer set search_path = public
as $$
  select a.plaza_base,
         coalesce(t.plaza_temporal, a.plaza_base),
         t.id is not null,
         t.id,
         coalesce(t.plaza_temporal_id, e.plaza_id)
  from public.activadores a
  left join public.equipos e on e.id = a.equipo_id
  left join lateral (
    select pt.id, pt.plaza_temporal, pt.plaza_temporal_id
    from public.activador_plaza_temporal pt
    where pt.activador_id = a.usuario_id
      and pt.cancelado_at is null
      and p_momento >= pt.inicio and p_momento < pt.fin
    order by pt.inicio desc limit 1
  ) t on true
  where a.usuario_id = p_activador_id
    and (auth.uid() is null or auth.uid() = p_activador_id);
$$;

create or replace function public.snapshot_organizacion_activacion()
returns trigger language plpgsql security definer set search_path = public
as $$
declare
  v_momento timestamptz := coalesce(new.created_at, now());
  v_equipo public.equipos%rowtype;
  v_lider_id uuid;
  v_plaza record;
begin
  -- Una importacion que ya trae identidad de equipo conserva su snapshot y completa sus IDs de plaza.
  if new.equipo_id_registro is not null then
    select plaza_id into new.plaza_base_id_registro
    from public.equipos where id = new.equipo_id_registro;
    select id into new.plaza_efectiva_id_registro from public.plazas
    where nombre_normalizado = lower(unaccent(btrim(
      coalesce(new.plaza_efectiva_registro, new.plaza_temporal, new.ciudad_activacion)
    )));
    new.plaza_efectiva_id_registro := coalesce(new.plaza_efectiva_id_registro, new.plaza_base_id_registro);
    new.plaza_id_registro := coalesce(new.plaza_id_registro, new.plaza_efectiva_id_registro);
    return new;
  end if;
  select e.* into v_equipo
  from public.activador_equipo_historial h
  join public.equipos e on e.id = h.equipo_id
  where h.activador_id = new.usuario_id
    and v_momento >= h.inicio and (h.fin is null or v_momento < h.fin)
  order by h.inicio desc limit 1;

  if v_equipo.id is null then
    select e.* into v_equipo from public.activadores a join public.equipos e on e.id = a.equipo_id
    where a.usuario_id = new.usuario_id;
  end if;

  select h.lider_id into v_lider_id from public.equipo_lider_historial h
  where h.equipo_id = v_equipo.id
    and v_momento >= h.inicio and (h.fin is null or v_momento < h.fin)
  order by h.inicio desc limit 1;

  select * into v_plaza from public.plaza_efectiva_activador(new.usuario_id, v_momento);
  new.equipo_id_registro := v_equipo.id;
  new.plaza_base_id_registro := v_equipo.plaza_id;
  new.plaza_efectiva_id_registro := coalesce(v_plaza.plaza_efectiva_id, v_equipo.plaza_id);
  new.plaza_id_registro := new.plaza_efectiva_id_registro;
  new.equipo_numero_registro := v_equipo.numero;
  new.equipo_nombre_registro := v_equipo.nombre;
  new.facturador_id_registro := v_equipo.facturador_id;
  select nombre into new.facturador_nombre_registro from public.facturadores where id = v_equipo.facturador_id;
  new.lider_id_registro := coalesce(v_lider_id, v_equipo.lider_actual_id);
  select nombre into new.lider_nombre_registro from public.activadores where usuario_id = new.lider_id_registro;
  new.plaza_base_registro := v_plaza.plaza_base;
  new.plaza_efectiva_registro := coalesce(v_plaza.plaza_efectiva, new.ciudad_activacion);
  new.plaza_temporal_registro := coalesce(v_plaza.es_temporal, false);
  new.plaza_temporal_asignacion_id := v_plaza.asignacion_id;
  return new;
end;
$$;

drop trigger if exists trg_snapshot_organizacion_activacion on public.activaciones;
create trigger trg_snapshot_organizacion_activacion
before insert on public.activaciones
for each row execute function public.snapshot_organizacion_activacion();

-- Backfill compatible: conserva los valores historicos existentes cuando no hay snapshot.
update public.activaciones ac
set equipo_id_registro = coalesce(ac.equipo_id_registro, a.equipo_id),
    plaza_base_id_registro = coalesce(ac.plaza_base_id_registro, e.plaza_id),
    plaza_efectiva_id_registro = coalesce(
      ac.plaza_efectiva_id_registro,
      (select pt.id from public.plazas pt
       where pt.nombre_normalizado = lower(unaccent(btrim(
         coalesce(ac.plaza_temporal, ac.ciudad_activacion, a.plaza_base, a.plaza)
       )))),
      e.plaza_id
    ),
    plaza_id_registro = coalesce(
      ac.plaza_id_registro,
      (select pt.id from public.plazas pt
       where pt.nombre_normalizado = lower(unaccent(btrim(
         coalesce(ac.plaza_temporal, ac.ciudad_activacion, a.plaza_base, a.plaza)
       )))),
      e.plaza_id
    ),
    equipo_numero_registro = coalesce(ac.equipo_numero_registro, e.numero),
    equipo_nombre_registro = coalesce(ac.equipo_nombre_registro, e.nombre),
    facturador_id_registro = coalesce(ac.facturador_id_registro, e.facturador_id),
    facturador_nombre_registro = coalesce(ac.facturador_nombre_registro, f.nombre),
    lider_id_registro = coalesce(ac.lider_id_registro, a.lider_id, e.lider_actual_id),
    lider_nombre_registro = coalesce(ac.lider_nombre_registro, l.nombre),
    plaza_base_registro = coalesce(ac.plaza_base_registro, a.plaza_base, a.plaza),
    plaza_efectiva_registro = coalesce(ac.plaza_efectiva_registro, ac.plaza_temporal, ac.ciudad_activacion),
    plaza_temporal_registro = coalesce(ac.es_plaza_temporal, false)
from public.activadores a
left join public.equipos e on e.id = a.equipo_id
left join public.facturadores f on f.id = e.facturador_id
left join public.activadores l on l.usuario_id = coalesce(a.lider_id, e.lider_actual_id)
where ac.usuario_id = a.usuario_id;

create index if not exists idx_activaciones_equipo_fecha on public.activaciones(equipo_id_registro, fecha_activacion);
create index if not exists idx_activaciones_facturador_fecha on public.activaciones(facturador_id_registro, fecha_activacion);
create index if not exists idx_activaciones_lider_fecha on public.activaciones(lider_id_registro, fecha_activacion);
create index if not exists idx_activaciones_plaza_fecha on public.activaciones(plaza_id_registro, fecha_activacion);
create index if not exists idx_plaza_temporal_vigencia on public.activador_plaza_temporal(activador_id, inicio, fin) where cancelado_at is null;

-- Reasignacion transaccional de relaciones operativas antes de eliminar una plaza.
create or replace function public.reasignar_y_eliminar_plaza(p_plaza_origen uuid, p_plaza_destino uuid)
returns jsonb language plpgsql security definer set search_path = public as $$
declare v_destino public.plazas%rowtype; v_reasignados jsonb;
begin
  if p_plaza_origen = p_plaza_destino then raise exception 'La plaza de destino debe ser distinta'; end if;
  select * into v_destino from public.plazas where id = p_plaza_destino and activa for update;
  if v_destino.id is null then raise exception 'La plaza de destino no existe o esta inactiva'; end if;
  if exists (select 1 from public.equipo_lider_historial where plaza_id = p_plaza_origen)
     or exists (select 1 from public.activaciones where plaza_id_registro = p_plaza_origen or plaza_base_id_registro = p_plaza_origen or plaza_efectiva_id_registro = p_plaza_origen)
  then raise exception 'No se puede reasignar de forma segura: existe historial o activaciones históricas vinculadas. Debe deshabilitarse.'; end if;
  update public.equipos set plaza_id = p_plaza_destino where plaza_id = p_plaza_origen;
  update public.activadores set plaza_id = p_plaza_destino, plaza_base = v_destino.nombre, plaza = v_destino.nombre where plaza_id = p_plaza_origen;
  update public.activador_plaza_temporal set plaza_temporal_id = p_plaza_destino where plaza_temporal_id = p_plaza_origen;
  delete from public.plazas where id = p_plaza_origen;
  return jsonb_build_object('equipos', (select count(*) from public.equipos where plaza_id = p_plaza_destino), 'plaza_destino', p_plaza_destino);
end $$;

alter table public.facturadores enable row level security;
alter table public.plazas enable row level security;
alter table public.equipos enable row level security;
alter table public.equipo_lider_historial enable row level security;
alter table public.activador_equipo_historial enable row level security;
alter table public.activador_plaza_temporal enable row level security;

revoke all on function public.asignar_lider_equipo(uuid,uuid,timestamptz,text) from public, anon, authenticated;
revoke all on function public.asignar_activador_equipo(uuid,uuid,timestamptz,text) from public, anon, authenticated;
revoke all on function public.asignar_equipos_lider(uuid,uuid[],timestamptz,text) from public, anon, authenticated;
revoke all on function public.actualizar_equipo_organizacion(uuid,text,uuid,uuid,boolean,timestamptz,text) from public, anon, authenticated;
revoke all on function public.reasignar_y_eliminar_plaza(uuid,uuid) from public, anon, authenticated;
grant execute on function public.asignar_lider_equipo(uuid,uuid,timestamptz,text) to service_role;
grant execute on function public.asignar_activador_equipo(uuid,uuid,timestamptz,text) to service_role;
grant execute on function public.asignar_equipos_lider(uuid,uuid[],timestamptz,text) to service_role;
grant execute on function public.actualizar_equipo_organizacion(uuid,text,uuid,uuid,boolean,timestamptz,text) to service_role;
grant execute on function public.reasignar_y_eliminar_plaza(uuid,uuid) to service_role;
revoke all on function public.plaza_efectiva_activador(uuid,timestamptz) from public, anon;
grant execute on function public.plaza_efectiva_activador(uuid,timestamptz) to authenticated, service_role;

commit;
